### ISSUE TITLE
Error while migrating database

### ISSUE THREAD

**Issue by SchinkTasia** [indentlabs/notebook#1311]
Hello,
After 1 year i want to install notebook.ai on a new system (Debian) and while migrating i got the following error.
I need to say, that i have experience in NodeJS but i dont really understand Ruby 🥴

```
username@hostname:~/homepage/notebook$ rake db:migrate
RAILS_GROUPS is unset; defaulting to web,worker
[Warning] Failed to detect RailsAdmin npm package, did you run "yarn install"?
== 20140713043535 CreateModels: migrating =====================================
-- create_table(:characters, {:id=>:integer})
   -> 0.0022s
-- create_table(:items, {:id=>:integer})
   -> 0.0009s
-- create_table(:locations, {:id=>:integer})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 3, expected 2)
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:405:in "column"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:54:in "block (2 levels) in attachment"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:52:in "each_pair"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:52:in "block in attachment"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:51:in "each"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:51:in "attachment"
/home/username/homepage/notebook/db/migrate/20140713043535_create_models.rb:101:in "block in change"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:100:in "block in create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:35:in "block in create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:314:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:929:in "block in method_missing"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in "block in say_with_time"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in "say_with_time"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:918:in "method_missing"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:35:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:100:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:160:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:198:in "create_table"
/home/username/homepage/notebook/db/migrate/20140713043535_create_models.rb:94:in "change"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:867:in "exec_migration"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:851:in "block (2 levels) in migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:850:in "block in migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in "with_connection"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:849:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1037:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1329:in "block in execute_migration_in_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1380:in "block in ddl_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in "block in transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:319:in "block in within_new_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in "block (2 levels) in synchronize"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in "handle_interrupt"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in "block in synchronize"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in "handle_interrupt"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in "synchronize"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in "within_new_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in "transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/transactions.rb:209:in "transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1380:in "ddl_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1328:in "execute_migration_in_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in "each"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in "migrate_without_lock"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1253:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1086:in "up"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1061:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/tasks/database_tasks.rb:237:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/railties/databases.rake:92:in "block (3 levels) in <top (required)>"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/railties/databases.rake:90:in "each"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/railties/databases.rake:90:in "block (2 levels) in <top (required)>"
/home/username/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in "eval"
/home/username/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in "<main>"

Caused by:
ArgumentError: wrong number of arguments (given 3, expected 2)
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:405:in "column"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:54:in "block (2 levels) in attachment"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:52:in "each_pair"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:52:in "block in attachment"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:51:in "each"
/home/username/.rvm/gems/ruby-3.2.1/gems/paperclip-6.1.0/lib/paperclip/schema.rb:51:in "attachment"
/home/username/homepage/notebook/db/migrate/20140713043535_create_models.rb:101:in "block in change"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:100:in "block in create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:35:in "block in create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:314:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:929:in "block in method_missing"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in "block in say_with_time"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in "say_with_time"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:918:in "method_missing"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:35:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:100:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:160:in "create_table"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration/compatibility.rb:198:in "create_table"
/home/username/homepage/notebook/db/migrate/20140713043535_create_models.rb:94:in "change"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:867:in "exec_migration"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:851:in "block (2 levels) in migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:850:in "block in migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in "with_connection"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:849:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1037:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1329:in "block in execute_migration_in_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1380:in "block in ddl_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in "block in transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:319:in "block in within_new_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in "block (2 levels) in synchronize"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in "handle_interrupt"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in "block in synchronize"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in "handle_interrupt"
/home/username/.rvm/gems/ruby-3.2.1/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in "synchronize"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in "within_new_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in "transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/transactions.rb:209:in "transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1380:in "ddl_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1328:in "execute_migration_in_transaction"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in "each"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in "migrate_without_lock"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1253:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1086:in "up"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1061:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/tasks/database_tasks.rb:237:in "migrate"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/railties/databases.rake:92:in "block (3 levels) in <top (required)>"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/railties/databases.rake:90:in "each"
/home/username/.rvm/gems/ruby-3.2.1/gems/activerecord-6.1.7.2/lib/active_record/railties/databases.rake:90:in "block (2 levels) in <top (required)>"
/home/username/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in "eval"
/home/username/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in "<main>"
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Additional to mention that "username" and "hostname" are placeholders in this log.
I replaced the username and hostname manually.

When i do "yarn install" before migrating the database it would work, but after that it cant find the "billing" table.

What can i do?

**Comment by drusepth** [comment]
Hey there! Thanks a ton for this bug report; it looks like some very old migrations were having some issues with some older gems.

I've gone ahead and (I think) resolved this issue on the `migration-fix` branch, but I'm not comfortable merging it into `master` without a lot more testing (specifically because of the big gem change from `paperclip` to `kt-paperclip`, although I've been meaning to make this change for a while now...).

Would you be able to switch to the `migration-fix` branch and try using that instead? I think it should work for you, and also give me some peace of mind that everything works while I do some more testing before merging that PR.

To do so, just:

```
git pull
git checkout migration-fix
```

Then, you should be able to `rake db:migrate` without errors. If you have any errors though, I'd also try a quick `bundle exec rake db:drop; bundle exec rake db:create db:migrate` to start the migrations from scratch since I did end up making some minor changes to old migrations that might need to be re-run.

Do let me know if that works for you! I think this is the right fix, but I just want to take some time to make sure nothing breaks with these changes; just figured I'd get you the solution sooner rather than later!

**Comment by SchinkTasia** [comment]
Hey,
Thank you very much for the help and dont worry about the branch ;)

It looks like its working, but i got another Error, when starting the server:

```
username@hostname:~/homepage/notebook$ ./bin/webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/username/homepage/notebook/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/username/homepage/notebook/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/username/homepage/notebook/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/username/homepage/notebook/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/username/homepage/notebook/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/username/homepage/notebook/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/username/homepage/notebook/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/username/homepage/notebook/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/username/homepage/notebook/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/username/homepage/notebook/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/username/homepage/notebook/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/username/homepage/notebook/node_modules/babel-loader/lib/index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.1
```

I am able to fix this with `export NODE_OPTIONS=--openssl-legacy-provider` but than my console get spammed with:
```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```

Do you have any clue to resolve this error?
Best Regards

**Comment by SchinkTasia** [comment]
Its me again :D

I can make an `yarn add "@babel/plugin-proposal-private-property-in-object"` to solve this, but than i got the following:
```
username@hostname:~/homepage/notebook./bin/webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/username/homepage/notebook/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20em, 16) or calc(20em / 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $fa-fw-width:          (20em / 16);
   │                         ^^^^^^^^^
   ╵
    node_modules/@fortawesome/fontawesome-free/scss/_variables.scss 12:25  @import
    node_modules/@fortawesome/fontawesome-free/scss/solid.scss 5:9         @import
    node_modules/rails_admin/src/rails_admin/styles/base.scss 15:9         @import
    app/javascript/stylesheets/rails_admin.scss 1:9                        root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(4em, 3) or calc(4em / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
6 │   font-size: (4em / 3);
  │               ^^^^^^^
  ╵
    node_modules/@fortawesome/fontawesome-free/scss/_larger.scss 6:15     @import
    node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 8:9  @import
    node_modules/rails_admin/src/rails_admin/styles/base.scss 16:9        @import
    app/javascript/stylesheets/rails_admin.scss 1:9                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(3em, 4) or calc(3em / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
7 │   line-height: (3em / 4);
  │                 ^^^^^^^
  ╵
    node_modules/@fortawesome/fontawesome-free/scss/_larger.scss 7:17     @import
    node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 8:9  @import
    node_modules/rails_admin/src/rails_admin/styles/base.scss 16:9        @import
    app/javascript/stylesheets/rails_admin.scss 1:9                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($fa-li-width * 5, 4) or calc($fa-li-width * 5 / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
6 │   margin-left: $fa-li-width * 5/4;
  │                ^^^^^^^^^^^^^^^^^^
  ╵
    node_modules/@fortawesome/fontawesome-free/scss/_list.scss 6:16        @import
    node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 10:9  @import
    node_modules/rails_admin/src/rails_admin/styles/base.scss 16:9         @import
    app/javascript/stylesheets/rails_admin.scss 1:9                        root stylesheet

ℹ ｢wdm｣: Hash: 7f724acd744cf89521d0
Version: webpack 4.46.0
Time: 7732ms
Built at: 01/18/2024 7:43:08 AM
                                                   Asset      Size               Chunks                         Chunk Names
                  js/application-b594b6a002f762b430cd.js  4.08 MiB          application  [emitted] [immutable]  application
              js/application-b594b6a002f762b430cd.js.map  3.99 MiB          application  [emitted] [dev]        application
                  js/rails_admin-378e8d84d058c645267f.js  2.79 MiB          rails_admin  [emitted] [immutable]  rails_admin
              js/rails_admin-378e8d84d058c645267f.js.map  2.94 MiB          rails_admin  [emitted] [dev]        rails_admin
             js/server_rendering-619adad9303ad64f6e3d.js  4.08 MiB     server_rendering  [emitted] [immutable]  server_rendering
         js/server_rendering-619adad9303ad64f6e3d.js.map  3.99 MiB     server_rendering  [emitted] [dev]        server_rendering
    js/vendors~actioncable-ab7f5ff3036cbee5fde7.chunk.js  31.6 KiB  vendors~actioncable  [emitted] [immutable]  vendors~actioncable
js/vendors~actioncable-ab7f5ff3036cbee5fde7.chunk.js.map  25.7 KiB  vendors~actioncable  [emitted] [dev]        vendors~actioncable
                                           manifest.json  1.67 KiB                       [emitted]
              media/webfonts/fa-solid-900-1551f4f6.woff2  76.4 KiB                       [emitted]
                media/webfonts/fa-solid-900-7a8b4f13.svg   897 KiB                       [emitted]
                media/webfonts/fa-solid-900-9bbb245e.eot   198 KiB                       [emitted]
                media/webfonts/fa-solid-900-be9ee23c.ttf   198 KiB                       [emitted]
               media/webfonts/fa-solid-900-eeccf4f6.woff  99.3 KiB                       [emitted]
ℹ ｢wdm｣: Compiled successfully.
```

But when i try to connect to http://localhost:3035/ i got an site-loading error without logs.
There is nothing in the console of notebook.ai or webbrowser.

**Comment by drusepth** [comment]
Hey! Sorry about the delay in response on this, but hopefully the fact that it should be a simple fix should be good news:

`./bin/webpack-dev-server` actually just runs a small server that listens to asset changes and recompiles them when any changes are detected -- you'll still also need to run `rails server` in another console window in order to run the actual server. Of note: if you're _not_ making changes to assets (e.g. changing javascript, css, etc) you shouldn't actually need to run `./bin/webpack-dev-server` at all, just `rails server`. 

When you run `rails server` in a console, you should be able to access the site at http://localhost:3000/ (not port 3035). Again, sorry about the delay on this, but I hope this helps!

**Comment by drusepth** [comment]
Hey! Just wanted to check in and see if everything is still working. It sounds like you were able to get this working so I'll close this issue, but feel free to reopen it or create another if you have any other problems!
