### ISSUE TITLE
Unable to execute rake task (data_migrations:create_default_billing_plans)

### ISSUE THREAD

**Issue by chozandrias76** [indentlabs/notebook#317]
### Expected behavior
Database is initialized with BillingPlans
### Actual behavior
```
rake data_migrations:create_default_billing_plans RAILS_ENV=development --trace
** Invoke data_migrations:create_default_billing_plans (first_time)
** Invoke environment (first_time)
** Execute environment
W, [2019-01-07T19:21:41.920291 #17905]  WARN -- Skylight: [SKYLIGHT] [3.1.2] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
** Execute data_migrations:create_default_billing_plans
Setting default billing plan for test.test@
rake aborted!
Couldn't find one of the necessary plans for this task -- check for free-for-life and starter stripe plan IDs
/home/xenos/Projects/notebook/lib/tasks/data_migrations.rake:50:in `block (3 levels) in <top (required)>'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/home/xenos/Projects/notebook/lib/tasks/data_migrations.rake:43:in `block (2 levels) in <top (required)>'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/xenos/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/xenos/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/xenos/.rvm/gems/ruby-2.5.1/bin/rake:23:in `load'
/home/xenos/.rvm/gems/ruby-2.5.1/bin/rake:23:in `<main>'
/home/xenos/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/xenos/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => data_migrations:create_default_billing_plans

```
### Steps to reproduce the behavior
`rake data_migrations:create_default_billing_plans`
On Ubuntu CLI via Windows 10 Emulator

**Comment by chozandrias76** [comment]
Running `rake billing_plans:initialize_defaults RAILS_ENV=development` seems to resolve the issue. I don't know if this step is required for all platforms, but might be good to add to the wiki.

**Comment by drusepth** [comment]
Good catch! I added it to the README's setup instructions.
